#!/usr/bin/env bash

set -euo pipefail

if [[ -z "${1:-}" ]]; then
  echo "usage: $(basename "$0") Title of the lesson learnt"
  exit 1
fi

title="$*"
filename=${title,,}

shopt -s extglob
directory=${filename//+([^a-z0-9_-])/-}-$(date +"%Y%m%d%H%M")
directory=${directory//+(-)/-}
shopt -u extglob

path="${0%/*}/journal/$directory"
mkdir -p "$path"
filepath="$path"/README.md
touch "$path"
echo "# $title"$'\n\n' > "$filepath"
"$EDITOR" "$filepath" -c "norm: cd ~/dev/lessons" -c "norm G"
