#!/usr/bin/env bash

set -euo pipefail

mark_begin='### Table of Contents'
mark_end='> _n'\''joy!_'
toc=""

while IFS= read -r file; do
  title=$(head -n1 "$file")
  toc+="1. [${title//# /}]($file)\n"
done < <(find journal -name "*.md" -type f)

lb=$(grep -ne "$mark_begin" README.md) || true
le=$(grep -ne "$mark_end" README.md) || true

# remove anything after the colon in the title found by grep
# https://stackoverflow.com/a/15988793/2119863
# life's too short :(
lb="${lb%%:*}"
le="${le%%:*}"

if [[ $lb != "" ]] && [[ $le != "" ]]; then
  sed "$lb,$le d" README.md > /tmp/readme.md
  cat /tmp/readme.md > README.md
fi

echo -e "$mark_begin\n\n$toc\n$mark_end" >> README.md
