#!/usr/bin/env bash

set -euo pipefail

mark_begin='### Table of Contents'
mark_end='> _n'\''joy!_'
toc=""

while IFS= read -r file; do
  title=$(head -n1 "$file")
  toc+="1. [${title//# /}]($file)\n"
done < <(find journal -name "*.md" -type f)

removing=false

while IFS= read -r line; do

  if ! "$removing" && [[ $line =~ $mark_begin ]]; then
    removing=true
    echo -e "$mark_begin\n" >> README.md.new
    echo -e "$toc" >> README.md.new
  fi

  if "$removing" && [[ $line =~ $mark_end ]]; then
    removing=false
  fi

  if ! "$removing"; then
    echo -e "$line" >> README.md.new
  fi

done < README.md

mv README.md.new README.md

echo reindexed
