#!/usr/bin/env bash

set -euo pipefail

mark_begin='### Table of Contents'
mark_end='> _n'\''joy!_'
toc=""

while IFS= read -r file; do
  title=$(head -n1 "$file")
  toc+="1. [${title//# /}]($file)\n"
done < <(find journal -name "*.md" -type f)

lb=$(grep -ne "$mark_begin" README.md | head -n 1 | awk -F: '{print $1}') || true
le=$(grep -ne "$mark_end" README.md | head -n 1 | awk -F: '{print $1}') || true

if [[ $lb != "" ]] && [[ $le != "" ]]; then
  sed "$lb,$le d" README.md > /tmp/readme.md
  cat /tmp/readme.md > README.md
fi

echo -e "$mark_begin\n\n$toc\n$mark_end" >> README.md

cat README.md
